common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
"""
/common/으로 시작하는 URL은 모두 common/urls.py 파일을 참조

로그인 기능은 django.contrib.auth 앱을 사용할 것. 그래서 common/views_copy.py 파일은 수정할 필요x. 
-> django.contrib.auth 앱의 LoginView 클래스를 사용


"""
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # 로그아웃 - {% url 'common:logout' %} 에 해당하는 매핑
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원가입 URL 매핑 - login.html 파일의 {% url 'common:signup' %}
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
# include 함수를 임포트해 forum/의 URL 매핑을
# path('forum/', views.index)에서 path('forum/', include('forum.urls'))로 수정
from forum.views import base_views

# 장고가 사용자의 페이지 요청을 이해할 수 있도록 config/urls.py 파일을 수정
# 이를 'URL 매핑을 추가한다' 고 말함
# config/urls.py 파일은 페이지 요청 시 가장 먼저 호출되며, 요청 URL 과 뷰 함수를 1:1로 연결해준다.

"""
URL 은 웹 브라우저에 입력한 localhost:8000/forum 에서 호스트명 localhost 와 포트 번호 :8000이 생략된 
forum/ 이다. 호스트명과 포트는 장고가 실행되는 환경에 따라 변하는 값이며 장고가 이미 알고 있는 값이다. 
그러므로 urlpatterns 에는 호스트명과 포트를 입력하지 않는다.

config/urls.py 파일을 수정했음에도 
cmd 창에 AttributeError: module 'forum.views' has no attribute 'index' 
이런 오류가 발생한 이유는 URL 매핑에 추가한 뷰 함수인 views.index가 없기 때문
-> forum/views_copy.py 파일에 index 함수를 추가하자.
"""
urlpatterns = [
    path('admin/', admin.site.urls),
    # forum/로 시작되는 페이지 요청은 모두 forum/urls.py 파일에 있는 URL 매핑을 참고하여 처리하라는 의미
    # -> forum 앱과 관련된 URL 요청은 앞으로 forum/urls.py 파일에서 관리하라는 뜻
    path('forum/', include('forum.urls')),
    # common 앱의 urls.py 파일을 사용하기 위해 -> /common/ 으로 시작하는 URL 은 common/urls.py 파일을 참조
    path('common/', include('common.urls')),

    # 로그인 성공시 '/' 에 해당되는 path
    # settings.py 의 LOGIN_REDIRECT_URL
    path('', base_views.index, name='index'),
]

# 서버 환경의 404 오류 페이지(404 오류 발생 시), page_not_found 함수가 호출되도록 함.
handler404 = 'common.views.page_not_found'

forum/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

"""
코드 내용은 기존 config/urls.py 파일과 다르지 않다.
다만 path('', views.index) 입력 부분만 다르다. config/urls.py 파일에서 forum/에 대한 처리를 한 상태에서
forum/urls.py 파일이 실행되므로 첫 번째 매개변수에 forum/가 아닌 빈 문자열('')을 인자로 넘겨준 것

path('<int:question_id>/', views.detail),
질문 게시판을 클릭시 http://localhost:8000/forum/1/ 이렇게 변경되는데 이는 Question 모델 데이터 중 id값이 1인 데이터를 조회하라이다.
question_id 에 1 이라는 값이 저장되고 views.detail 함수가 실행된다.
int:는 question_id에 숫자가 매핑되었음을 의미
장고는 forum/까지는 config/urls.py의 URL 매핑을, 그 뒤 /1 은 forum/urls.py 의 매핑을 참고할 것이다.
매핑을 완료했으면 forum/views_copy.py 에서 화면을 추가해줘야한다.
"""

# 네임스페이스 추가(향후 forum 기능(앱)뿐이 아니라 추가 앱들이 있을 때 같은 URL 별칭 사용을 피하도록)
# 여기서 추가했으면 템플릿에서도 추가해줘야 한다. question_list.html 파일에
# <li><a href="{% url 'forum:detail' question.id %}">{{ question.subject }}</a></li> 이렇게.
app_name = 'forum'

urlpatterns = [

    # base_views.py
    # URL 하드코딩의 한계를 없애기 위해 name 을 사용해 별칭을 붙인다.
    # 이렇게 하면 주소 /forum/은 index라는 URL 별칭, /forum/2/는 detail이라는 URL 별칭이 생긴다.
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # answer_views.py
    # form 엘리먼트의 action 속성에 있는 {% url 'forum:answer_create' question.id %}에
    # 해당하는 URL 매핑이 없기 때문에 아래와 같이 등록해야함.
    # 상세 화면에서 <질문답변> 버튼을 눌렀을 때 작동할 form 엘리먼트의 /forum/answer/create/2/에 대한 URL 매핑을 추가한 것
    # 답변, 수정, 삭제 매핑 추가
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # question_views.py
    # 질문등록하기, 질문수정버튼, 질문 삭제 매핑 추가
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),


    # 댓글 매핑(등록, 수정, 삭제)
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),

    # 답변 댓글 매핑 - 댓글 등록은 답변 id, 댓글수정/삭제 는 댓글 id
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # 질문, 답변 추천 기능 매핑
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

forum/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
# get_object_or_404 주소 잘못입력했을 경우 404 페이지 출력을 위해 추가함
# 답변을 생성한 후 상세 화면을 호출하려면 redirect 함수를 사용. redirect 함수는 함수에 전달된 값을 참고하여 페이지 이동을 수행

# 페이징 기능을 위해 추가하는 클래스 - Paginator
from django.core.paginator import Paginator

# views 디렉터리에 파일이 위치하므로 ..models
from ..models import Question
# 목록 정렬을 위해 Count 추가
from django.db.models import Q, Count

# forum 로거 생성(forum 에서 직접 로그를 출력하도록 설정 - 로그 파일에 로그를 출력하기 위해서 모듈추가)
import logging
logger = logging.getLogger('forum')


# - index 함수의 매개변수 request 는 장고에 의해 자동으로 전달되는 HTTP 요청 객체이다.
# - request 는 사용자가 전달한 데이터를 확인할 때 사용된다.
def index(request):
    """
    forum 목록
    """
    logger.info("INFO 레벨로 출력")

    # 입력 파라미터 - 페이지, 검색어
    # GET 방식 요청 URL에서 page값을 가져올 때 사용 ex. localhost:8000/forum/?page=1
    # page = request.GET.get('page', '1')
    # 페이지
    page = request.GET.get('page', '1')
    # 검색어
    kw = request.GET.get('kw', '')

    # Question 모델을 임포트해 Question 모델 데이터를 작성한 날짜의 역순으로 조회하기 위해 order_by 함수사용

    # question_list = Question.objects.order_by('-create_date')
    # 정렬기준
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        # 최신순 정렬
        # '-create_date'는 - 기호가 앞에 붙어 있으므로 작성일시의 역순을 의미
        question_list = Question.objects.order_by('-create_date')

    # 조회
    if kw:
        question_list = question_list.filter(
            # 제목
            Q(subject__icontains=kw) |
            # 내용
            Q(content__icontains=kw) |
            # 질문 글쓴이
            Q(author__username__icontains=kw) |
            # 답변 글쓴이
            Q(answer__author__username__icontains=kw)
        ).distinct()

    # 페이징 처리 - 페이지당 10개씩
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    # page, kw, so 추가 - 입력받은 값을 searchForm 에 전달하기 위해
    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}

    # # render 함수가 템플릿을 HTML로 변환하는 과정에서 사용되는 데이터
    # context = {'question_list': question_list}

    # render 함수는 context에 있는 Question 모델 데이터 question_list를 forum/question_list.html 파일에
    # 적용하여 HTML 코드로 변환한다. 장고에서는 이런 파일(forum/question_list.html)을 템플릿이라 한다.
    return render(request, 'forum/question_list.html', context)
    # return HttpResponse("안녕. 게시판 방문을 환영해.")


def detail(request, question_id):
    """
    forum 내용
    """
    # question_id 가 URL 매핑에 있던 question_id이다.
    # 즉, /forum/1/ 페이지가 호출되면 최종으로 detail 함수의 매개변수 question_id에 1이 전달
    # question = Question.objects.get(id=question_id)

    # get_object_or_404 함수는 모델의 기본키를 이용하여 모델 객체 한 건을 반환한다.
    # pk에 해당하는 건이 없으면 오류 대신 404 페이지를 반환
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'forum/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- forum CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Forum</title>
</head>
<body>

<!-- 장고 - 템플릿 특정 위치에 파일을 삽입하는 include 기능 -->
{% include "navbar.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>

<!-- 자바스크립트 - jQuery 실행을 위해 -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

<!--
HTML 표준구조는 body 엘리먼트 바깥 부분은 모두 같은 내용으로 중복된다.
그리고 CSS 파일 이름이 변경되거나 새로운 CSS 파일이 추가되면
head 엘리먼트의 내용을 수정하려고 템플릿 파일을 일일이 찾아다녀야 하는 불편함도 있다.
이를 위해 장고는 템플릿 상속(extends) 기능을 제공한다.

<!doctype html> 위에 빨간 줄 떠도 괜찮.
-->

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        <!-- 필드 오류 출력 -->
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    <!-- 넌필드 오류 출력 -->
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

<!--
로그인 실패시 원인 2가지
필드오류(입력값 누락 or 형식이 맞지 않을 경우)
넌필드 오류(입력값과 관계없이 발생한 오류)
-->

templates/navbar.html
<!-- 장고 - 템플릿 특정 위치에 파일을 삽입하는 include 기능 -->
<!-- 네비게이션바 - 모든페이지에 보이도록. 메인페이로 이동. -->
<!-- 로고(클래스값 navbar-brand)를 가장 왼쪽, 으론쪽은 로그인 링크 -->
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'forum:index' %}">Forum</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                <!-- 로그인 후에는 로그인 링크가 로그아웃 링크로 바뀌도록 -->
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                {% else %}

                <!-- 따로 만든 로그인 구현 common 폴더와 연결 -->
                <a class="nav-link" href="{% url 'common:login' %}">로그인</a>

                {% endif %}
            </li>
        </ul>
    </div>
</nav>